### ISSUE TITLE
Cropping UI not working on react-native 0.50

### ISSUE THREAD

**Issue by falloutcoder** [doo/scanbot-sdk-example-react-native#1]
Tested using android, the image cropping functionality is not working. The drag able points to crop the image are not responsive. Working fine with react-native 0.48 but not with 0.50.

**Comment by eddyfrank** [comment]
Fixed: Upgraded this example app to the latest versions of `react` and `react-native` as well as `react-native-scanbot-sdk@1.0.8`
(see https://github.com/doo/scanbot-sdk-example-react-native/commit/b14428793baf1500d67fe79f1b1aaf64af914e2b)
