### ISSUE TITLE
Identifier 'resizeImage' has already been declared 

### ISSUE THREAD

**Issue by MITDD6338** [doo/scanbot-sdk-example-react-native#12]
Identifier 'resizeImage' has already been declared (54:15)

 **async function resizeImage(image = {}, quality = 'original') {
             ^
     if (quality === 'original') {
        return images;
     }**

this error can fetch node_module 
Someone can help me

**Comment by eddyfrank** [comment]
This is not related to Scanbot SDK. There is no such function `resizeImage(..)` in the Scanbot SDK node module or this example app.
We hope for your kind understanding that we cannot provide support for any 3rd-party modules.
