### ISSUE TITLE
latest version support RN

### ISSUE THREAD

**Issue by enrique26** [doo/scanbot-sdk-example-react-native#13]
hi
which is the latest version of react native that would support this version of scanbot-sdk?

**Comment by tailsu** [comment]
Hi,

So far we've tested only with RN 57. We haven't tested 58 or 59, but the breaking changes in those versions do not affect the SDK from what I can tell, so I'd expect them to work as well.

As always, do try the SDK with the RN version that you have in mind and if you stumble into problems, open a new issue. I'll be glad to help you out with any integration problem that you might encounter.
