### ISSUE TITLE
issue running on RN 59.0 android

### ISSUE THREAD

**Issue by enrique26** [doo/scanbot-sdk-example-react-native#14]
#13
Hi 
I having problems using the module on RN 59.9.
creating a new proyect and following the instruccions on the documentation .
i get the next message when i try to build the app.

```
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find io.scanbot:sdk-package-ui:1.33.3.
     Required by:
         project :app > project :react-native-scanbot-sdk
   > Could not find io.scanbot:sdk-package-4:1.33.3.
     Required by:
         project :app > project :react-native-scanbot-sdk
```

i had a success running on RN 58.6. but even in that version i had to change a few configutations to make it run.

**for RN 58.6 for android version only**
**this is my android/build.gradle**
add configuration **subprojects**
and modify the com.android.tools.build:gradle to 3.2.1
```
buildscript {
    ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://nexus.scanbot.io/nexus/content/repositories/releases/'
        }
        maven {
            url 'https://nexus.scanbot.io/nexus/content/repositories/snapshots/'
        }

    }
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.2"
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.7'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

**And for android/app/build.gradle**
add **multiDexEnabled true**
```
defaultConfig {
        ...
        multiDexEnabled true
    }
```
and change the line **implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"** for **implementation "com.android.support:appcompat-v7:25.3.1"**
```
dependencies {
    ....
    implementation "com.android.support:appcompat-v7:25.3.1"
   ...
}
```
with these changes can run the application and the module works fine so far

i have tried do the same on RN 59.9,  but with no success .

i hope you can help me to find the correct configuration to achive this.

Thanks

**Comment by tailsu** [comment]
`Could not find io.scanbot:sdk-package-ui:1.33.3` suggests that these lines are missing from `android/build.gradle`:
```
        maven {
            url 'https://nexus.scanbot.io/nexus/content/repositories/releases/'
        }
        maven {
            url 'https://nexus.scanbot.io/nexus/content/repositories/snapshots/'
        }
```
At any rate 1.33.3 is rather old. I'd suggest that you also look into upgrading to the latest version.

**Comment by enrique26** [comment]
> `Could not find io.scanbot:sdk-package-ui:1.33.3` suggests that these lines are missing from `android/build.gradle`:
> 
> ```
>         maven {
>             url 'https://nexus.scanbot.io/nexus/content/repositories/releases/'
>         }
>         maven {
>             url 'https://nexus.scanbot.io/nexus/content/repositories/snapshots/'
>         }
> ```
> 
> At any rate 1.33.3 is rather old. I'd suggest that you also look into upgrading to the latest version.


hi @tailsu , thanks for your answer.

yeah, i already add those lines. 
Sorry i forgot to add the log after add those lines on my first description.

- **creating a new proyect with the last version of react native (59.9).**
- **installing the module with "npm install --save react-native-scanbot-sdk" and linking the dependencies**
- **adding the lines that you mention (and the documentation mention as well)**
- **and finally i add multiDexEnabled to android/app/build.gradle  defaultconfig**

i get the next message:

````
> Task :app:transformNativeLibsWithMergeJniLibsForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
````

**Comment by eddyfrank** [comment]
@enrique26 

> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'
Solution:
```
android {
  ...
  packagingOptions {
      pickFirst '**/libc++_shared.so'
  }
}
```
(recently added to our docs https://scanbotsdk.github.io/documentation/react-native/)

Also, please try the latest release version `react-native-scanbot-sdk@3.0.0` which is compatible with the latest RN versions (see the changelog https://scanbotsdk.github.io/documentation/react-native/#releaseHistory).
