### ISSUE TITLE
error: cannot access ImageFilterType import io.scanbot.sdk.process.ImageFilterType

### ISSUE THREAD

**Issue by basemanabulsi** [doo/scanbot-sdk-example-react-native#15]
Hello I am facing a problem while building the SDK for Android; which I am getting an error with **Task :react-native-scanbot-sdk:compileDebugJavaWithJavac**

> \scanbot-sdk-example-react-native\node_modules\react-native-scanbot-sdk\android\app\src\main\java\io\scanbot\sdk\reactnative\BitmapHelper.java:25: error: cannot access ImageFilterType
> import io.scanbot.sdk.process.ImageFilterType;

> 
>   bad class file: .gradle\caches\transforms-2\files-2.1\d160afb4ade9b25d035bb8a38ef44725\jars\classes.jar(/io/scanbot/sdk/process/ImageFilterType.class)
>     bad RuntimeInvisibleParameterAnnotations attribute: ImageFilterType(int,String)
>     Please remove or make sure it appears in the correct subdirectory of the classpath.

Also, I tried an empty project with the same steps of the documentation on two devices with different operating system (Linux, Windows) but I got the same error.  

I don't know if the problem in my configuration or with the SDK. 

Thank you.

**Comment by tailsu** [comment]
I haven't seen this before. Can you send us the project that you're trying to build?

**Comment by basemanabulsi** [comment]
Here it is I uploaded it to my repository, it is the same as the example.

`https://github.com/basemanabulsi/scanbot`

**Comment by tailsu** [comment]
It might be a corrupted gradle cache. Delete ~/.gradle and try again. I see reports online that the problem is reproducible only in certain versions of the JDK. Make sure that you have version 28 of the Android SDK installed with the latest updates.

**Comment by basemanabulsi** [comment]
It didn't work, I tried it on two devices and downloaded all the SDKs in android studio and deleted .gradle cache and reinstall the whole gradle from the device and reinstall it but it keeps giving me error. This is the whole error that I got  :

> 
>  react-native run-android
> Starting JS server...
> Building and installing the app on the device (cd android && ./gradlew installDebug)...
> Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> 
> > Configure project :app
> WARNING: The following project options are deprecated and have been removed: 
> android.useDeprecatedNdk
> NdkCompile is no longer supported
> 
> 
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
> WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
> WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
> 
> > Configure project :react-native-camera-kit
> WARNING: The following project options are deprecated and have been removed: 
> android.useDeprecatedNdk
> NdkCompile is no longer supported
> 
> 
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> 
> > Configure project :react-native-navigation
> WARNING: The following project options are deprecated and have been removed: 
> android.useDeprecatedNdk
> NdkCompile is no longer supported
> 
> 
> downloadRobolectricDependencies /home/al-nabulsi/Desktop/Temp/scanbot-sdk-example-react-native/android/build/robolectric-dependencies
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> 
> > Configure project :react-native-scanbot-sdk
> WARNING: The following project options are deprecated and have been removed: 
> android.useDeprecatedNdk
> NdkCompile is no longer supported
> 
> 
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> 
> > Task :react-native-camera-kit:compileDebugJavaWithJavac
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: /home/al-nabulsi/Desktop/Temp/scanbot-sdk-example-react-native/node_modules/react-native-camera-kit/android/src/main/java/com/wix/RNCameraKit/gallery/GalleryViewManager.java uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> > Task :react-native-navigation:compileDebugJavaWithJavac
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 
> > Task :react-native-scanbot-sdk:compileDebugJavaWithJavac FAILED
> /home/al-nabulsi/Desktop/Temp/scanbot-sdk-example-react-native/node_modules/react-native-scanbot-sdk/android/app/src/main/java/io/scanbot/sdk/reactnative/ScanbotSDKReactNative.java:34: error: cannot access ImageFilterType
> import io.scanbot.sdk.process.ImageFilterType;
>                              ^
>   bad class file: /home/al-nabulsi/.gradle/caches/transforms-2/files-2.1/02f0d5ffef9f249a507e4ef9df3df859/jars/classes.jar(/io/scanbot/sdk/process/ImageFilterType.class)
>     bad RuntimeInvisibleParameterAnnotations attribute: ImageFilterType(int,String)
>     Please remove or make sure it appears in the correct subdirectory of the classpath.
> /home/al-nabulsi/Desktop/Temp/scanbot-sdk-example-react-native/node_modules/react-native-scanbot-sdk/android/app/src/main/java/io/scanbot/sdk/reactnative/ui/DefaultUiModule.java:42: error: cannot access BaseJavaModule
> public class DefaultUiModule extends ReactContextBaseJavaModule {
>        ^
>   bad class file: /home/al-nabulsi/.gradle/caches/transforms-2/files-2.1/a3ee773e259eccb8aa03f84a943303da/jars/classes.jar(/com/facebook/react/bridge/BaseJavaModule.class)
>     bad RuntimeInvisibleParameterAnnotations attribute: BaseJavaModule()
>     Please remove or make sure it appears in the correct subdirectory of the classpath.
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-scanbot-sdk:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 1m 29s
> 33 actionable tasks: 33 executed
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html
>

**Comment by basemanabulsi** [comment]
The problem solved in version 3.x
Thank you for your support.
