### ISSUE TITLE
InitializeSDK: Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by meldsz** [doo/scanbot-sdk-example-react-native#17]
![Screenshot_2019-07-31-16-29-44-974_io unitekscanner demo reactnative](https://user-images.githubusercontent.com/11755694/62225685-da530280-b3b0-11e9-8612-08a87750a11f.png)
I get this error when I boot up the application and then the application freezes at bootup without displaying any screens. This happens very often and only sometimes does the app bootup correctly. What is the issue and how do I fix this?

**Comment by eddyfrank** [comment]
Looks like the initialization of the Scanbot SDK is triggered a bit too early - the RN main `Activity` as well as the application context are not ready yet.

How/where do you initialize the Scanbot SDK? Try to do it in the `componentDidMount()` method, as shown in our example app https://github.com/doo/scanbot-sdk-example-react-native/blob/master/src/App.js#L70

**Comment by meldsz** [comment]
Thanks! I had initialised the SDK in `componentWillMount()`. Changed it to `componentDidMount()` and it did not throw the error. Not Yet!
