### ISSUE TITLE
Cannot read property 'major' of undefined

### ISSUE THREAD

**Issue by janmisek1** [doo/scanbot-sdk-example-react-native#4]
App not start. Only error "Cannot read property 'major' of undefined" is shown.

Update react native in package.json  ` "react-native": "^0.55.3",` fix it for me.

**Comment by eddyfrank** [comment]
Fixed: Upgraded this example app to the latest versions of `react` and `react-native` as well as `react-native-scanbot-sdk@1.0.8`
(see https://github.com/doo/scanbot-sdk-example-react-native/commit/b14428793baf1500d67fe79f1b1aaf64af914e2b)
