### ISSUE TITLE
OCR not working

### ISSUE THREAD

**Issue by GuillermoGuevara** [doo/scanbot-sdk-example-react-native#7]
when i try use .getOCRConfigs() or performOCR the app crash, can help me please!

<img width="450" alt="captura de pantalla 2018-12-19 a la s 09 58 42" src="https://user-images.githubusercontent.com/17258085/50231846-4f6b4d80-0375-11e9-99d9-40d44857f9dd.png">

**Comment by tailsu** [comment]
The likely reason is that you don't have the `ScanbotSDKOCRData.bundle` included in your project. Can you check that?

**Comment by GuillermoGuevara** [comment]
Hi! thanks for response, yes its included, or can you tell me the right way to do this?
maybe i did it wrong

<img width="1436" alt="captura de pantalla 2018-12-19 a la s 10 58 45" src="https://user-images.githubusercontent.com/17258085/50235314-38c8f480-037d-11e9-8a28-5fa1ca46a2f6.png">

**Comment by GuillermoGuevara** [comment]
Ok! I will do.
thanks!

**Comment by eddyfrank** [comment]
We haven't received any updates on this issue and are assuming that this is solved.
