### ISSUE TITLE
Feature-Request

### ISSUE THREAD

**Issue by karvulf** [doo/scanbot-sdk-example-react-native#8]
Hi,
im interested in the Scanbot SDK, especially the OCR-part. 
Is it possible to get the position and width and height of every single word that is scanned?

**Comment by eddyfrank** [comment]
Hey @karvulf ,

thanks for the request and your patience.

The Scanbot OCR feature is based on the Tesseract OCR engine with some modifications and enhancements. In general you can get the following results from the Scanbot SDK API:

- a searchable PDF document with the recognized text layer (aka. sandwiched PDF document)
- recognized text as plain text
- bounding boxes of all recognized paragraphs, lines and words
- text results and confidence values for each bounding box.

The current implementation of our ReactNative plugin does not provide JS mappings for the bounding boxes. But we are working on it.

**Comment by eddyfrank** [comment]
@karvulf 

We have added this feature in the latest release version`react-native-scanbot-sdk@3.0.0` (see the full changelog: https://scanbotsdk.github.io/documentation/react-native/#releaseHistory). 

Use the option `outputFormat: 'FULL_OCR_RESULT'` to get full OCR results (bounding boxes of words, lines and paragraphs):

```
const result = await ScanbotSDK.performOCR(imageUris, ['en'], {outputFormat: 'FULL_OCR_RESULT'});
// the result is stored as JSON file: result.jsonFileUri
```

Docs: https://scanbotsdk.github.io/documentation/react-native/#module_ScanbotSDK.performOCR
