### ISSUE TITLE
Not working on OnePlus 6 androidP

### ISSUE THREAD

**Issue by obsd** [doo/scanbot-sdk-example-react-native#9]
I installed this app on my One Plus 6 and this crash when I installed on xiaomi A1 it works

**Comment by eddyfrank** [comment]
@obsd 
Did you check the log files (logcat) of this crash? 

If you are a paying customer or developing for a customer, please reach out to sdk@scanbot.io. Thanks.

**Comment by eddyfrank** [comment]
We haven't received any updates on this issue and are assuming that this is solved.
